import Head from 'next/head';
import {
  Box,
  Heading,
  Container,
  Button,
  Flex,
  Icon,
  useColorMode,
} from '@chakra-ui/react';
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import { WalletSection } from '../components';
import CollapseEx from '../components/CollapseB';
import CollapseS from '../components/CollapseS';
import CollapseQ from '../components/CollapseQ';


export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  
  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>Cosmos Cw20 Dashboard</title>
        <meta name="description" content="Generated by cosmos dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent="end" mb={4}>
        <Button variant="outline" px={0} onClick={toggleColorMode}>
          <Icon
            as={colorMode === 'light' ? BsFillMoonStarsFill : BsFillSunFill}
          />
        </Button>
      </Flex>
      <Box textAlign="center">
        <Heading
          as="h1"
          fontSize={{ base: '3xl', sm: '4xl', md: '5xl' }}
          fontWeight="extrabold"
          mb={3}
        >
          Cosmos Wallet App
        </Heading>
        <Heading
          as="h1"
          fontWeight="bold"
          fontSize={{ base: '2xl', sm: '3xl', md: '4xl' }}
        >
        </Heading>
      </Box>
      <WalletSection />
      <br />
      <CollapseEx />
      <br /><br />
      <CollapseS />
      <br />
      <CollapseQ />
    </Container>
  );
}
